# Generated by Django 3.1.4 on 2021-02-08 12:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_diet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.CharField(blank=True, max_length=200, unique=True)),
                ('rest_name', models.CharField(blank=True, max_length=200)),
                ('rest_url', models.CharField(blank=True, max_length=200)),
                ('rest_city', models.CharField(blank=True, max_length=200)),
                ('rest_street', models.CharField(blank=True, max_length=200)),
                ('map_url', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('rest_info', models.TextField(blank=True)),
                ('rest_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('price', models.CharField(blank=True, max_length=10)),
                ('rest_types', models.CharField(blank=True, max_length=200)),
                ('order_online', models.BooleanField(default=False)),
                ('safety_measures', models.BooleanField(default=False)),
                ('cuisine', models.ManyToManyField(blank=True, to='restaurants.Cuisine')),
                ('feature', models.ManyToManyField(blank=True, to='restaurants.Feature')),
                ('meals', models.ManyToManyField(blank=True, to='restaurants.Meal')),
                ('spec_diet', models.ManyToManyField(blank=True, to='restaurants.Diet')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_stars', models.CharField(max_length=200)),
                ('four_stars', models.CharField(max_length=200)),
                ('three_stars', models.CharField(max_length=200)),
                ('two_stars', models.CharField(max_length=200)),
                ('one_stars', models.CharField(max_length=200)),
                ('michelin_label', models.CharField(max_length=200)),
                ('trav_choice_label', models.CharField(max_length=200)),
                ('food_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('service_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('value_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('atmos_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('rest_total_reviews', models.IntegerField()),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('review_source', models.CharField(blank=True, max_length=200)),
                ('review_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
